'use server'

export async function generateToolkitAI(prompt: string) {
  try {
    const response = await fetch("https://integrate.api.nvidia.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${process.env.NEXT_PUBLIC_NVIDIA_API_KEY || ''}`
      },
      body: JSON.stringify({
        model: "meta/llama-3.1-8b-instruct",
        max_tokens: 1000,
        temperature: 0.7,
        messages: [
          { role: "system", content: "You are an expert technical hiring manager providing clear, helpful assistance. Do not output raw JSON, write in standard markdown format suitable for direct reading." },
          { role: "user", content: prompt }
        ]
      })
    })

    const data = await response.json()
    
    if (!response.ok) {
      throw new Error(data.error?.message || data.detail || "API call returned an error structure")
    }
    
    return { 
      success: true, 
      text: data.choices[0]?.message?.content || "No response generated by model." 
    }
  } catch (err: any) {
    return { 
      success: false, 
      error: `Server fetch error: ${err.message}` 
    }
  }
}
